systemProp.imVersion=5.1.0.4
systemProp.bioVersion=5.1.0.4
systemProp.blueGenesVersion=1.0.+

systemProp.javax.xml.stream.XMLOutputFactory=com.sun.xml.internal.stream.XMLOutputFactoryImpl
#useful when debugging since it seems to use a daemon when -Dorg.gradle.debug=true added to JAVA_OPTS, even when -Dorg.gradle.daemon=false also there
org.gradle.jvmargs=-Xmx48g -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
